// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// ICloudinaryService is an autogenerated mock type for the ICloudinaryService type
type ICloudinaryService struct {
	mock.Mock
}

// UploadImage provides a mock function with given fields: ctx, file, filename
func (_m *ICloudinaryService) UploadImage(ctx context.Context, file multipart.File, filename string) (string, error) {
	ret := _m.Called(ctx, file, filename)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multipart.File, string) (string, error)); ok {
		return rf(ctx, file, filename)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multipart.File, string) string); ok {
		r0 = rf(ctx, file, filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, multipart.File, string) error); ok {
		r1 = rf(ctx, file, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICloudinaryService creates a new instance of ICloudinaryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICloudinaryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICloudinaryService {
	mock := &ICloudinaryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
