// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IEmailSender is an autogenerated mock type for the IEmailSender type
type IEmailSender struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: to, subject, content
func (_m *IEmailSender) SendEmail(to string, subject string, content string) error {
	ret := _m.Called(to, subject, content)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(to, subject, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIEmailSender creates a new instance of IEmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEmailSender {
	mock := &IEmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
