// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	messaging "github.com/Amaankaa/Blog-Starter-Project/Domain/messaging"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// IMessagingUsecase is an autogenerated mock type for the IMessagingUsecase type
type IMessagingUsecase struct {
	mock.Mock
}

// CreateConversation provides a mock function with given fields: ctx, userID, participantIDs
func (_m *IMessagingUsecase) CreateConversation(ctx context.Context, userID primitive.ObjectID, participantIDs []primitive.ObjectID) (messaging.Conversation, error) {
	ret := _m.Called(ctx, userID, participantIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateConversation")
	}

	var r0 messaging.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, []primitive.ObjectID) (messaging.Conversation, error)); ok {
		return rf(ctx, userID, participantIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, []primitive.ObjectID) messaging.Conversation); ok {
		r0 = rf(ctx, userID, participantIDs)
	} else {
		r0 = ret.Get(0).(messaging.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, []primitive.ObjectID) error); ok {
		r1 = rf(ctx, userID, participantIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConversation provides a mock function with given fields: ctx, id
func (_m *IMessagingUsecase) GetConversation(ctx context.Context, id primitive.ObjectID) (messaging.Conversation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetConversation")
	}

	var r0 messaging.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (messaging.Conversation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) messaging.Conversation); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(messaging.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessages provides a mock function with given fields: ctx, userID, conversationID, limit, offset
func (_m *IMessagingUsecase) GetMessages(ctx context.Context, userID primitive.ObjectID, conversationID primitive.ObjectID, limit int, offset int) ([]messaging.Message, error) {
	ret := _m.Called(ctx, userID, conversationID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []messaging.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID, int, int) ([]messaging.Message, error)); ok {
		return rf(ctx, userID, conversationID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID, int, int) []messaging.Message); ok {
		r0 = rf(ctx, userID, conversationID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]messaging.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.ObjectID, int, int) error); ok {
		r1 = rf(ctx, userID, conversationID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserConversations provides a mock function with given fields: ctx, userID, limit, offset
func (_m *IMessagingUsecase) GetUserConversations(ctx context.Context, userID primitive.ObjectID, limit int, offset int) ([]messaging.Conversation, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserConversations")
	}

	var r0 []messaging.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int, int) ([]messaging.Conversation, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int, int) []messaging.Conversation); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]messaging.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessage provides a mock function with given fields: ctx, senderID, conversationID, content
func (_m *IMessagingUsecase) SendMessage(ctx context.Context, senderID primitive.ObjectID, conversationID primitive.ObjectID, content string) (messaging.Message, error) {
	ret := _m.Called(ctx, senderID, conversationID, content)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 messaging.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string) (messaging.Message, error)); ok {
		return rf(ctx, senderID, conversationID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string) messaging.Message); ok {
		r0 = rf(ctx, senderID, conversationID, content)
	} else {
		r0 = ret.Get(0).(messaging.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, primitive.ObjectID, string) error); ok {
		r1 = rf(ctx, senderID, conversationID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIMessagingUsecase creates a new instance of IMessagingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMessagingUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMessagingUsecase {
	mock := &IMessagingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
