name: ShareSpace Backend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.24'
  MONGODB_URI: mongodb://localhost:27017/sharespace_test

jobs:
  # Test and Build Job
  test-and-build:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Install mockery
      run: go install github.com/vektra/mockery/v2@latest

    - name: Generate mocks
      run: |
        mockery --all --dir=Domain/user --output=mocks
        mockery --all --dir=Domain/mentorship --output=mocks

    - name: Run linter
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m

    - name: Create test environment file
      run: |
        echo "MONGODB_URI=${{ env.MONGODB_URI }}" > .env
        echo "JWT_SECRET=test-secret-key-for-ci" >> .env
        echo "REFRESH_SECRET=test-refresh-secret-for-ci" >> .env
        echo "CLOUDINARY_CLOUD_NAME=test" >> .env
        echo "CLOUDINARY_API_KEY=test" >> .env
        echo "CLOUDINARY_API_SECRET=test" >> .env
        echo "EMAIL_FROM=test@example.com" >> .env
        echo "EMAIL_PASSWORD=test" >> .env

    - name: Run tests
      run: |
        go test -v -race -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

    - name: Build application
      run: |
        go build -o bin/sharespace-backend ./Delivery
        chmod +x bin/sharespace-backend

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sharespace-backend-${{ github.sha }}
        path: |
          bin/sharespace-backend
          coverage.html

  # Security Scanning
  security-scan:
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run Gosec Security Scanner
      run: gosec -fmt sarif -out gosec.sarif ./...

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: gosec.sarif
      if: always()

  # Docker Build and Push
  docker-build:
    runs-on: ubuntu-latest
    needs: [test-and-build, security-scan]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/sharespace-backend
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Deploy to Render (Automatic via Git)
  deploy-notification:
    runs-on: ubuntu-latest
    needs: [test-and-build, security-scan]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
    - name: Deployment notification
      run: |
        echo "🚀 Code pushed to ${{ github.ref_name }} branch"
        echo "📦 Render will automatically deploy from this commit"
        echo "🔗 Check deployment status at: https://dashboard.render.com"

    - name: Wait for deployment
      run: |
        echo "⏳ Waiting 60 seconds for Render deployment..."
        sleep 60

    - name: Health check
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "🏥 Checking production health..."
          curl -f ${{ secrets.RENDER_PRODUCTION_URL }}/health || echo "❌ Production health check failed"
        elif [ "${{ github.ref_name }}" = "develop" ]; then
          echo "🏥 Checking staging health..."
          curl -f ${{ secrets.RENDER_STAGING_URL }}/health || echo "❌ Staging health check failed"
        fi
