name: ShareSpace Backend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.24'

jobs:
  # Build Only (Tests Temporarily Disabled)
  build-only:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install dependencies
      run: go mod download

    - name: Build application
      run: |
        mkdir -p bin
        go build -o bin/sharespace-backend ./Delivery
        chmod +x bin/sharespace-backend

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sharespace-backend-${{ github.sha }}
        path: bin/sharespace-backend

  # Security Scanning (Temporarily Disabled)
  security-scan:
    runs-on: ubuntu-latest
    needs: build-only

    steps:
    - name: Security scan placeholder
      run: |
        echo "Security scan temporarily disabled"
        echo "Will be re-enabled after core pipeline is working"

  # Docker Build and Push
  docker-build:
    runs-on: ubuntu-latest
    needs: [build-only, security-scan]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/sharespace-backend
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Deploy to Render (Automatic via Git)
  deploy-notification:
    runs-on: ubuntu-latest
    needs: [build-only, security-scan]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
    - name: Deployment notification
      run: |
        echo "🚀 Code pushed to ${{ github.ref_name }} branch"
        echo "📦 Render will automatically deploy from this commit"
        echo "🔗 Check deployment status at: https://dashboard.render.com"

    - name: Wait for deployment
      run: |
        echo "⏳ Waiting 60 seconds for Render deployment..."
        sleep 60

    - name: Health check
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "🏥 Checking production health..."
          curl -f ${{ secrets.RENDER_PRODUCTION_URL }}/health || echo "❌ Production health check failed"
        elif [ "${{ github.ref_name }}" = "develop" ]; then
          echo "🏥 Checking staging health..."
          curl -f ${{ secrets.RENDER_STAGING_URL }}/health || echo "❌ Staging health check failed"
        fi
